source 'https://rubygems.org'


group :development do
  gem 'pry'  
  gem 'shotgun'
end

gem 'rack-flash3'
gem 'sinatra'
gem 'thin'
gem 'json'
gem 'require_all'
gem 'data_mapper'
gem 'dm-sqlite-adapter'

